# --- !Ups
CREATE TABLE TASKS(
  `ID` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `AUTHOR_ID` INTEGER NOT NULL,
  `TITLE` TEXT NOT NULL,
  `DESCRIPTION` TEXT NOT NULL,
  `STATE` TEXT NOT NULL
);

# --- !Downs
DROP TABLE `TASKS`;